### ISSUE TITLE
Entre em contato Comigo!

### ISSUE THREAD

**Issue by mateusmirandaalmeida** [libertas-cris/n8n-backups#1]
Somos da Z-API e precisamos conversar com você.

**Comment by libertas-cris** [comment]
olá

Em seg., 23 de set. de 2024 às 14:11, Mateus Miranda <
***@***.***> escreveu:

**Comment by mateusmirandaalmeida** [comment]
entre em contato com suporte da z-api pelo numero +55 44 9839-8733 e diga que deseja falar com Mateus Miranda
